### ISSUE TITLE
APT & YUM version constraint?

### ISSUE THREAD

**Issue by Sauraus** [p4paul/chef-perforce#11]
Does the Perforce cookbook really need to lock the YUM & APT cookbook versions? It seems that for a 'low' level cookbook like Perforce to lock these cookbooks causes more issues than its worth as it prevents other cookbooks from moving forward.

I vote for removing the version constraint on APT & YUM from the cookbook entirely because it is something that should be done at the base / environment cookbook level.

**Comment by dhoer** [comment]
I will accept a pr with it removed.

**Comment by dhoer** [comment]
I would even accept dropping these dependencies altogether and using the apt package introduced and chef 12.9 and yum package introduced in chef 12.14.  So `chef_version '>= 12.14'` would be the min version.

**Comment by Sauraus** [comment]
Don't forget about supermarket please. :)
