### ISSUE TITLE
Incompatible windows version

### ISSUE THREAD

**Issue by ghost** [p4paul/chef-perforce#2]
Hello,

Our chef setup has (for now) frozen the windows cookbook to 1.36.
This cookbook has a dependency on 1.38. Do you really need 1.38? Can this be set to 1.36?

Better yet -> Is it possible to say that look for windows cookbook only if installing on windows? (I am doing this for centos)

Thanks

Ajay
(chef noob)

**Comment by dhoer** [comment]
That could be relaxed to just be '~> 1.0'.  Can you please submit a PR and I will release it as soon as the build is green?

**Comment by dhoer** [comment]
To fix those rubocop issues, run `bundle update`, then `bundle exec rubocop -a`.  It should correct those offenses automatically.

**Comment by ghost** [comment]
All set.

Thanks

Ajay Gautam
Office:  646.454.4648

From: Dennis Hoer
Reply-To: dhoer/chef-perforce
Date: Thursday, January 21, 2016 at 4:03 PM
To: dhoer/chef-perforce
Cc: Ajay Gautam
Subject: Re: [chef-perforce] Incompatible windows version (#2)

bundle exec rubocop -a

**Comment by ghost** [comment]
So… Does this get auto-promoted to chef marketplace, or is there manual intervention involved.

(Trying to get an ETA of when I can use it)

Thanks

Ajay Gautam
Office:  646.454.4648

From: Dennis Hoer
Reply-To: dhoer/chef-perforce
Date: Thursday, January 21, 2016 at 4:38 PM
To: dhoer/chef-perforce
Cc: Ajay Gautam
Subject: Re: [chef-perforce] Incompatible windows version (#2)

Closed #2https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dhoer_chef-2Dperforce_issues_2&d=CwMCaQ&c=Y88mj8G9kqbn8Ggg2-NXMw&r=xnO0tfku-bhkJ1CNBZbzs1SUTQPF_LPVtf_QQsYeKQ4&m=dCN4meAufLDnVbA2zRatWXFqkvTO3SoI4HbdMKSMBPI&s=eqHOQblW0iBn48C8m9m2jzLauyueIw9HoEIb2RKZ9Yo&e= via 9ebf944https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dhoer_chef-2Dperforce_commit_9ebf9444bde9cda57e7b9614c5085487abdbb36a&d=CwMCaQ&c=Y88mj8G9kqbn8Ggg2-NXMw&r=xnO0tfku-bhkJ1CNBZbzs1SUTQPF_LPVtf_QQsYeKQ4&m=dCN4meAufLDnVbA2zRatWXFqkvTO3SoI4HbdMKSMBPI&s=KUe9v1dmucrRzM20gHz42Ol57d1yPrvMcmZuwYQKPOw&e=.
