### ISSUE TITLE
Platform fedora not supported

### ISSUE THREAD

**Issue by J-cztery** [p4paul/chef-perforce#5]
I am trying to use perforce cookbook on fedora-23 and it fails with "Platform fedora not supported"

==> default:
==> default: RuntimeError
==> default: ------------
==> default: Platform fedora not supported!
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/perforce/recipes/default.rb:44:in `from_file'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/perforce/recipes/default.rb:
==> default:
==> default:  37:
==> default:  38:    windows_package 'Helix P4 Command-Line Client' do
==> default:  39:      source "#{node['perforce']['download_url']}/#{node['perforce']['release']}/bin.nt#{bit}/helix-p4-#{bit}.exe"
==> default:
==> default:  40:      options '/v"/qn"'
==> default:
==> default:  41:      installer_type :custom
==> default:
==> default:  42:    end
==> default:  43:  else
==> default:
==> default:  44>>   fail(fail_msg)
==> default:
==> default:  45:  end
==> default:  46:
==> default:
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux

**Comment by dhoer** [comment]
You are more than welcome to submit a pull request to support Fedora.

**Comment by J-cztery** [comment]
Here you go: https://github.com/dhoer/chef-perforce/pull/6

**Comment by dhoer** [comment]
Released 1.3.0
